-- ------------------------
-- 1. TABLA USUARIO -------
-- ------------------------

-- INSERT
CREATE OR REPLACE PROCEDURE SP_INSERT_USUARIO
(
PNOMBRE_USUARIO IN VARCHAR,
PAPELLIDO_USUARIO IN VARCHAR,
PEMAIL_USUARIO IN VARCHAR,
PPASSWORD_USUARIO IN VARCHAR
) AS
BEGIN
    INSERT INTO USUARIO (NOMBRE_USUARIO, APELLIDO_USUARIO, EMAIL_USUARIO, PASSWORD_USUARIO)
    VALUES(PNOMBRE_USUARIO, PAPELLIDO_USUARIO, PEMAIL_USUARIO, PPASSWORD_USUARIO);
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_INSERT_USUARIO;

-- UPDATE
create or replace PROCEDURE SP_UPDATE_TEL_USUARIO
(
    PID_USUARIO IN NUMBER,
    PTELEFONO_USUARIO IN VARCHAR
) AS
BEGIN
    UPDATE USUARIO SET TELEFONO_USUARIO = PTELEFONO_USUARIO
    WHERE ID_USUARIO = PID_USUARIO;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_UPDATE_TEL_USUARIO;

-- DELETE
create or replace PROCEDURE SP_DELETE_USUARIO
(
    PID_USUARIO IN NUMBER
) AS
BEGIN
    DELETE FROM USUARIO 
    WHERE ID_USUARIO = PID_USUARIO;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_DELETE_USUARIO;

-- ------------------------------
-- 2. TABLA TIPO HABITACION -----
-- ------------------------------

-- INSERT
CREATE OR REPLACE PROCEDURE SP_INSERT_TIPOHABITACION
(
    PNOMBRE IN VARCHAR,
    PDESCRIPCION IN VARCHAR,
    PPRECIO IN NUMBER,
    PCANTIDAD IN NUMBER
) AS
BEGIN
    INSERT INTO TIPOHABITACION (NOMBRE_TIPOHABITACION, DESCRIPCION_TIPOHABITACION, PRECIO_TIPOHABITACION, CAPACIDAD_TIPOHABITACION)
    VALUES(PNOMBRE, PDESCRIPCION, PPRECIO, PCANTIDAD);
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_INSERT_TIPOHABITACION;

-- UPDATE
create or replace PROCEDURE SP_UPDATE_PRECIO_TIPOHABITACION
(
    PID_TIPOHABITACION IN NUMBER,
    PPRECIO_TIPOHABITACION IN NUMBER
) AS
BEGIN
    UPDATE TIPOHABITACION SET PRECIO_TIPOHABITACION = PPRECIO_TIPOHABITACION
    WHERE ID_TIPOHABITACION = PID_TIPOHABITACION;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_UPDATE_PRECIO_TIPOHABITACION;

-- DELETE
create or replace PROCEDURE SP_DELETE_TIPOHABITACION
(
    PID_TIPOHABITACION IN NUMBER
) AS
BEGIN
    DELETE FROM TIPOHABITACION 
    WHERE ID_TIPOHABITACION = PID_TIPOHABITACION;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_DELETE_TIPOHABITACION;


-- ------------------------
-- 3. TABLA RESERVAS -------
-- ------------------------

-- INSERT
CREATE OR REPLACE PROCEDURE SP_INSERT_RESERVA
(
    P_CHECK_IN IN DATE,
    P_CHECK_OUT IN DATE,
    P__ESTADO IN VARCHAR
) AS
BEGIN
    INSERT INTO RESERVA (CHECKIN_RESERVA, CHECKOUT_RESERVA, ESTADO_RESERVA)
    VALUES(P_CHECK_IN, P_CHECK_OUT, P__ESTADO);
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_INSERT_RESERVA;

-- UPDATE
create or replace PROCEDURE SP_UPDATE_CHECKIN_RESERVA
(
    PID_RESERVA IN NUMBER,
    P_CHECK_IN IN DATE
) AS
BEGIN
    UPDATE RESERVA SET CHECKIN_RESERVA = P_CHECK_IN
    WHERE ID_RESERVA = PID_RESERVA;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_UPDATE_CHECKIN_RESERVA;

-- DELETE

create or replace PROCEDURE SP_DELETE_RESERVA
(
    PID_RESERVA IN NUMBER
) AS
BEGIN
    DELETE FROM RESERVA 
    WHERE ID_RESERVA = PID_RESERVA;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_DELETE_RESERVA;

-- -------------------------
-- 4. TABLA HABITACION -----
-- -------------------------

-- INSERT
CREATE OR REPLACE PROCEDURE SP_INSERT_HABITACION
(
    PPISO_HABITACION IN NUMBER,
    P_TIPOHABITACION IN NUMBER
) AS
BEGIN
    INSERT INTO HABITACION (PISO_HABITACION, ID_TIPO_HABITACION)
    VALUES(PPISO_HABITACION, P_TIPOHABITACION);
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_INSERT_HABITACION;

-- UPDATE
create or replace PROCEDURE SP_UPDATE_TIPOHABITACION_HABITACION
(
    PID_HABITACION IN NUMBER,
    P_ID_TIPOHABITACION IN NUMBER
) AS
BEGIN
    UPDATE HABITACION SET ID_TIPO_HABITACION = P_ID_TIPOHABITACION
    WHERE ID_HABITACION = PID_HABITACION;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_UPDATE_TIPOHABITACION_HABITACION;

-- DELETE
create or replace PROCEDURE SP_DELETE_HABITACION
(
    PID_HABITACION IN NUMBER
) AS
BEGIN
    DELETE FROM HABITACION 
    WHERE ID_HABITACION = PID_HABITACION;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_DELETE_HABITACION;

-- -------------------------
-- 5. TABLA ACOMPANANTE -----
-- -------------------------

-- INSERT
CREATE OR REPLACE PROCEDURE SP_INSERT_ACOMPANANTE
(
    PNOMBRE_ACOMPANANTE IN VARCHAR,
    PAPELLIDO_ACOMPANANTE IN VARCHAR,
    PDOCUMENTO_ACOMPANANTE IN VARCHAR,
    PID_RESERVA_ACOMPANANTE IN NUMBER
) AS
BEGIN
    INSERT INTO ACOMPANANTE (NOMBRE_ACOMPANANTE, APELLIDO_ACOMPANANTE, DOCUMENTO_ACOMPANANTE, ID_RESERVA_ACOMPANANTE)
    VALUES(PNOMBRE_ACOMPANANTE, PAPELLIDO_ACOMPANANTE, PDOCUMENTO_ACOMPANANTE, PID_RESERVA_ACOMPANANTE);
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_INSERT_ACOMPANANTE;

-- UPDATE
create or replace PROCEDURE SP_UPDATE_DOCUMENTO_ACOMPANANTE
(
    PID_ACOMPANANTE IN NUMBER,
    PDOCUMENTO_ACOMPANANTE IN VARCHAR
) AS
BEGIN
    UPDATE ACOMPANANTE SET DOCUMENTO_ACOMPANANTE = PDOCUMENTO_ACOMPANANTE
    WHERE ID_ACOMPANANTE = PID_ACOMPANANTE;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_UPDATE_DOCUMENTO_ACOMPANANTE;

-- DELETE
create or replace PROCEDURE SP_DELETE_ACOMPANANTE
(
    PID_ACOMPANANTE IN NUMBER
) AS
BEGIN
    DELETE FROM ACOMPANANTE 
    WHERE ID_ACOMPANANTE = PID_ACOMPANANTE;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_DELETE_ACOMPANANTE;

-- -------------------------
-- 6. TABLA FACTURA --------
-- -------------------------

-- INSERT
CREATE OR REPLACE PROCEDURE SP_INSERT_FACTURA
(
    PMONTO_FACTURA IN NUMBER,
    PESTADO_PAGO IN VARCHAR,
    PID_RESERVA_FACTURA IN NUMBER
) AS
BEGIN
    INSERT INTO FACTURA (MONTO_FACTURA, ESTADO_PAGO_FACTURA, ID_RESERVA_FACTURA)
    VALUES(PMONTO_FACTURA, PESTADO_PAGO, PID_RESERVA_FACTURA);
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_INSERT_FACTURA;

-- UPDATE
create or replace PROCEDURE SP_UPDATE_FECHA_PAGO_FACTURA
(
    PID_FACTURA IN NUMBER,
    PFECHA_PAGO IN DATE
) AS 
BEGIN
    UPDATE FACTURA SET FECHA_PAGO_FACTURA = PFECHA_PAGO
    WHERE ID_FACTURA = PID_FACTURA;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_UPDATE_FECHA_PAGO_FACTURA;

-- DELETE
create or replace PROCEDURE SP_DELETE_FACTURA
(
    PID_FACTURA IN NUMBER
) AS
BEGIN
    DELETE FROM FACTURA 
    WHERE ID_FACTURA = PID_FACTURA;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_DELETE_FACTURA;

-- ---------------------------------
-- 6. TABLA HUESPED HABITACION -----
-- ---------------------------------

-- INSERT
--01
CREATE OR REPLACE PROCEDURE SP_INSERT_HUESPED_HUESPEDHABITACION
(
    PID_RESERVA IN NUMBER,
    PID_HABITACION IN NUMBER,
    PID_HUESPED IN NUMBER
) AS
BEGIN
    INSERT INTO HUESPEDHABITACION (ID_RESERVA_HUESPEDHABITACION, ID_HABITACION_HUESPEDHABITACION, ID_USUARIO_HUESPEDHABITACION)
    VALUES(PID_RESERVA, PID_HABITACION, PID_HUESPED);
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_INSERT_HUESPED_HUESPEDHABITACION;

--02
CREATE OR REPLACE PROCEDURE SP_INSERT_ACOMPANANTE_HUESPEDHABITACION
(
    PID_RESERVA IN NUMBER,
    PID_HABITACION IN NUMBER,
    PID_ACOMPANANTE IN NUMBER
) AS
BEGIN
    INSERT INTO HUESPEDHABITACION (ID_RESERVA_HUESPEDHABITACION, ID_HABITACION_HUESPEDHABITACION, ID_ACOMPANANTE_HUESPEDHABITACION)
    VALUES(PID_RESERVA, PID_HABITACION, PID_ACOMPANANTE);
    
    COMMIT;
    
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_INSERT_ACOMPANANTE_HUESPEDHABITACION;

-- UPDATE
create or replace PROCEDURE SP_UPDATE_HABITACION_HUESPEDHABITACION
(
    PID_HUESPEDHABITACION IN NUMBER,
    PID_HABITACION IN NUMBER
) AS 
BEGIN
    UPDATE HUESPEDHABITACION SET ID_HABITACION_HUESPEDHABITACION = PID_HABITACION
    WHERE ID_HUESPEDHABITACION = PID_HUESPEDHABITACION;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_UPDATE_HABITACION_HUESPEDHABITACION;

-- DELETE
create or replace PROCEDURE SP_DELETE_HUESPEDHABITACION
(
    PID_HUESPEDHABITACION IN NUMBER
) AS
BEGIN
    DELETE FROM HUESPEDHABITACION 
    WHERE ID_HUESPEDHABITACION = PID_HUESPEDHABITACION;

    COMMIT;

    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SP_DELETE_HUESPEDHABITACION;
-- -----------------
-- CUSRORES  -------
-- -----------------

-- TOP 3 HABITACIONES (RANGO DE FECHAS)
create or replace PROCEDURE SP_TOP_HABITACIONES(
    p_fecha_inicial IN DATE,
    p_fecha_final IN DATE
) AS

    CURSOR chabitaciones IS
    SELECT h.id_habitacion, COUNT(DISTINCT hh.id_reserva_huespedhabitacion) AS veces_elegida
        FROM HABITACION h 
        INNER JOIN HUESPEDHABITACION hh ON hh.id_habitacion_huespedhabitacion = h.id_habitacion 
        INNER JOIN RESERVA r ON hh.id_reserva_huespedhabitacion = r.id_reserva
        WHERE r.checkin_reserva BETWEEN p_fecha_inicial AND p_fecha_final
        GROUP BY h.id_habitacion 
        ORDER BY veces_elegida DESC 
        FETCH FIRST 3 ROWS ONLY;

    v_id_habitacion NUMBER;
    v_veces_elegida NUMBER;

BEGIN
    OPEN chabitaciones;
    LOOP
        FETCH chabitaciones INTO v_id_habitacion, v_veces_elegida;
        EXIT WHEN chabitaciones%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Habitacion: ' || v_id_habitacion || ' ' || v_veces_elegida);
    END LOOP;
    CLOSE chabitaciones;
END;

-- TOP 3 CLIENTES MAS RECURRENTES
create or replace PROCEDURE SP_TOP_CLIENTES(
    p_fecha_inicial IN DATE,
    p_fecha_final IN DATE
) AS

    CURSOR cusuarios IS
    SELECT u.id_usuario, u.nombre_usuario, COUNT(r.id_titular_reserva) AS Reservas_hechas
        FROM USUARIO u 
        INNER JOIN RESERVA r ON r.id_titular_reserva = u.id_usuario 
        WHERE r.checkin_reserva BETWEEN p_fecha_inicial AND p_fecha_final
        GROUP BY u.id_usuario, u.nombre_usuario
        ORDER BY Reservas_hechas DESC 
        FETCH FIRST 3 ROWS ONLY;

    v_id_usuario NUMBER;
    v_nombre_usuario VARCHAR(50);
    v_reservas_hechas NUMBER;

BEGIN
    OPEN cusuarios;
    LOOP
        FETCH cusuarios INTO v_id_usuario, v_nombre_usuario, v_reservas_hechas;
        EXIT WHEN cusuarios%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Huesped: ' || v_id_usuario || ' ' || v_nombre_usuario || ' ha hecho ' || v_reservas_hechas || ' reservas');
    END LOOP;
    CLOSE cusuarios;
END;

-- RESERVAS POR MES EN UN AÑO



BETWEEN DATE '2028-09-03' AND DATE '2028-09-08'